### ISSUE TITLE
GBA Offset Video Filter Source

### ISSUE THREAD

**Issue by allanrps** [drkhrse/drkhrse_miyoo_bezels#4]
Did you creat the video filter to offset the screen for the gba overlays? Do you have the source so that I could compile my own? I want to achieve a different offset amount.

**Comment by drkhrse** [comment]
No I did not. Depending on the system you should be able to use the custom video scaling settings to do your own offsets like in Jeltron’s Retro Overlay instructions. https://github.com/Jeltr0n/Retro-Overlays

**Comment by drkhrse** [comment]
Done

**Comment by drkhrse** [comment]
Done
